%YAML 1.1
---
superclass:
- dev/midso/runner/runner_interface.yaml
method:
- TrainRunner():
    args:
    - {type: const SolverInterface &, name: solver}
    - {type: const Network &, name: network}
- run()

